plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}
android {
    namespace 'com.workverse.app'
    compileSdk 36
    defaultConfig {
        applicationId "com.workverse.app"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"
        buildConfigField "String", "GEMINI_API_KEY", "\"AQ.Ab8RN6JeD8uslA9hmAIjAIjICz8aH_zVYeYQSWpycIok_6IPgQ\""
        buildConfigField "String", "GROQ_API_KEY", "\"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\""
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation platform('com.google.firebase:firebase-bom:32.7.2')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'androidx.activity:activity:1.13.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'com.google.ai.client.generativeai:generativeai:0.9.0'
}