package com.workverse.app.utils;

/**
 * Presentation-only helpers for AI feedback results.
 *
 * IMPORTANT: This class no longer performs any sentiment analysis. It used
 * to guess sentiment by counting positive/negative keywords, which is not
 * real AI analysis and could easily be wrong (e.g. "the response time was
 * too slow" contains no obviously negative keyword). Sentiment and score
 * are now generated by a real external AI (Anthropic API) inside the
 * GeminiFeedbackService (called directly from the app) and simply read from Firestore
 * (Feedback.getAiSentiment() / getAiScore()) — this class only formats
 * that already-computed result for display.
 */
public class AIFeedbackAnalyzer {

    public static final String SENTIMENT_POSITIVE = "Positive";
    public static final String SENTIMENT_NEGATIVE = "Negative";
    public static final String SENTIMENT_NEUTRAL  = "Neutral";

    /** Maps an AI score (0-100) to the human-readable band used across the app. */
    public static String getScoreBand(int score) {
        if (score >= 90) return "Excellent";
        if (score >= 80) return "Very Good";
        if (score >= 70) return "Good";
        if (score >= 60) return "Average";
        if (score >= 50) return "Needs Improvement";
        return "Poor";
    }

    /** Get color resource name for a sentiment badge. */
    public static String getSentimentColor(String sentiment) {
        if (sentiment == null) return "status_pending";
        switch (sentiment) {
            case SENTIMENT_POSITIVE: return "status_approved";   // green
            case SENTIMENT_NEGATIVE: return "status_rejected";   // red
            default:                 return "status_pending";    // orange
        }
    }

    /** Human-readable label for the async AI analysis lifecycle. */
    public static String getStatusLabel(String aiStatus) {
        if (aiStatus == null) return "AI Analysis: Pending";
        switch (aiStatus) {
            case "completed":  return "AI Analysis: Complete";
            case "processing": return "AI Analysis: In Progress…";
            case "failed":      return "AI Analysis: Failed (tap to retry)";
            default:            return "AI Analysis: Pending";
        }
    }
}
